site_name: The Digital Capability Publisher
repo_url: https://github.com/Digital-Business-Council/Digital-Capability-Publisher
pages:
    - 'Disclaimer': 'disclaimer.md'
    - 'Audience': 'index.md'
    - 'Overview': 'overview.md'
    - 'Conformance': 'conformance.md'
    - 'Distribution Pacakage': 'distributionpackage.md'
    - 'Terms and Definitions': 'termsanddefinitions.md'
    - 'Use Cases': 'usecases.md'
    - 'Service Metadata Publishing (SMP) Version 1.0 Profile (Normative)': 'servicemetadatapublishing.md'
    - 'Identifiers': 'identifiers.md'
    - 'Services Provided by the Capability Publisher': 'Capabilitypublisher-services.md'
    - 'APPENDIX A: Use Cases': 'appendixausecases.md'
theme: mkdocs
